name: HSP-HELLO-WORD
author: Heera Singh
description: Test Desc
inputs:
  who-to-greet:
    description: "who to greet"
    required: true
    default: Heera
outputs:
  time:
    description: "Greet time"
branding:
  icon: "thumbs-up"
  color: "white"
runs:
  using: "node12"
  main: "dist/index.js"
