on: push
jobs:
  hello-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Heera Singh"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
