name: checkout
on:
  push:
    branches:
      - master
      - develop
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
