name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "16.x"
      - name: Install Node Dependencies
        run: npm CI
      - name: Check Code Fromat
        run: npm run format:check
      - name: Run Tests and get Code-Coverage
        run: npm test -- --coverage
        env:
          CI: true