on: push
jobs:
  issue-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          title: Title
          body: Body
          assignees: |
            heerasinghmca
            hspsinghmca07
      - run: |
          echo "Output: ${{ steps.issue.outputs.issue }}"
