name: slack notificcation
on:
  release:
    types: [published]
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      name: slack-message
      run: |
        curl -X POST --data-urlencode "payload={\"channel\": \"#qa_channel_internal\", \"username\": \"webhookbot\", \"text\": \"New release ${{github.event_release.tag_name}} is out, <${{github.event_release.html_url}}, check it out now.> .\", \"icon_emoji\": \":ghost:\"}" ${{ secrets.SLACK_WEBHOOK }}
